### PR TITLE
Added 3.1.3 scripts

### PR DESCRIPTION
**Pull request by Jonic**
@tjvr Related to https://github.com/scratchblocks/scratchblocks/pull/268

Providing there are no changes to the above PR, this update adds the scripts to the scratchblocks.github.io domain, making them available to the Raspberry Pi Projects site. It doesn't make them available for THIS site though, not sure if that's a dealbreaker for you.

### CODE REVIEW

**Comment by tjvr** [comment]
As discussed, let's update this to the 3.2 code 🙂

I'm happy for you to link the scripts from this site, but are you sure that's a good idea? I don't want your projects site having missing scripts if GitHub Pages has an outage 🙈 Obviously up to you!

Ideally we would call these files simply `3.2`, and I'll update them with any bugfixes (that don't change the external API). I'll include them from the (now misleadingly-named) `v4/index.html` too, but absolutely not a blocker for this PR.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Jonic** [comment]
@tjvr We're already linking to the scripts from the Github Pages app, so we're happy continuing on with that. I'll chuck out this PR and its awful name and submit a new one. I'll also update the example app to use the 3.2 scripts by default, since that's the latest stable version.

**Comment by Jonic** [comment]
@tjvr Ok, so I'm looking at the files in this repo, and apparently there's already a 3.2 script in there. Am I missing something? I'm a bit confused about that, since it's from September, so can't possibly be the same as the one we've just merged in the main scratchblocks repo. Any thoughts?

**Comment by Jonic** [comment]
@tjvr I think for now I'll copy the files from the 3.2 release into our projects site and maybe leave this homepage alone for a bit. Seems that I might break something if I go changing stuff!

**Pull request closed without merging**
